name: mobile_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  chat_bubbles: ^1.2.0
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  firebase_storage: ^10.2.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.4.0
  google_sign_in: ^5.2.4
  intl: ^0.17.0
  json_annotation: ^4.0.1
  kiwi: ^4.0.2
  shared_preferences: ^2.0.13
  sign_button: ^2.0.2

dev_dependencies:
  analyzer: ^3.2.0
  build_runner: ^2.0.6
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  kiwi_generator: ^4.0.2

flutter:

  uses-material-design: true
