// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATvGphMRtOIcDVZjNFAsKQYnimsjmySNk',
    appId: '1:201695375938:web:0e05a98c434f0f0722b3db',
    messagingSenderId: '201695375938',
    projectId: 'live-chat-e86a6',
    authDomain: 'live-chat-e86a6.firebaseapp.com',
    storageBucket: 'live-chat-e86a6.appspot.com',
    measurementId: 'G-22BRP46KNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxq7fSB4qQ1o3PEFoFUcGjn0YWN91a-o',
    appId: '1:201695375938:android:65f71156c56bcd6622b3db',
    messagingSenderId: '201695375938',
    projectId: 'live-chat-e86a6',
    storageBucket: 'live-chat-e86a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWBR2AsQLphEN-EMV1PFxDoP-7lE412A',
    appId: '1:201695375938:ios:92220bf6c6d24cca22b3db',
    messagingSenderId: '201695375938',
    projectId: 'live-chat-e86a6',
    storageBucket: 'live-chat-e86a6.appspot.com',
    iosClientId: '201695375938-grt3fs56k5m5o1mperpqqj6lq5bq1or0.apps.googleusercontent.com',
    iosBundleId: 'com.myoganugraha.chat',
  );
}
